BEE Backport bacula/src/lib/openssl.c
This commit is the result of the squash of the following main commits:

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Mar 19 18:09:32 2020 +0100

    more work on QT5 for windows

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Wed Jan 8 14:40:42 2020 +0100

    Fix #5829 about OpenBSD compilation issue with TLS 1.3 code

    The SSL_R_APPLICATION_DATA_AFTER_CLOSE_NOTIFY seems to not be defined
    on OpenBSD. Probably a compatibility issue.

    Compiling openssl.c
    openssl.c: In function 'void openssl_post_errors(JCR*, int, const char*)':
    openssl.c:67: error: 'SSL_R_APPLICATION_DATA_AFTER_CLOSE_NOTIFY' was not declared in this scope

Author: Alain Spineux <alain@baculasystems.com>
Date:   Fri Jul 19 16:13:26 2019 +0200

    Fix OpenSSL TLS 1.3 message with ssl3_read_bytes:application data after close notify

      Ignore this error that is SSL_shutdown() specific and is new to TLS 1.3
      ERR=error:14094123:SSL routines:ssl3_read_bytes:application data after close notify
      we are doing the TLS shutdown.
      This can happens at multiple place but the message appears only on
      the DIR because at that time the connection with the DIR is often "terminated"