BEE Backport bacula/src/findlib/attribs.c
This commit is the result of the squash of the following main commits:

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Wed Aug 14 14:23:03 2019 +0200

    Move acl/permission BEEF code to bee_XXX.c/h files

Author: Alain Spineux <alain@baculasystems.com>
Date:   Tue Oct 23 11:13:14 2018 +0200

    win32: fix Error: findlib/attribs.c:1040 Error in GetFileAttributesExW

    - we were reading Windows attributes from the "live" filesystem instead
      of the VSS snapshot one.

Author: Alain Spineux <alain@baculasystems.com>
Date:   Tue Apr 24 18:36:54 2018 +0200

    win32: win_error() parameter from POOLMEM* to const char *ofile

    - their is no reason to use a POOLMEM* and I will use a char* parameter
    - I prefer to "adjust" the type of the parameter

Author: Alain Spineux <alain@baculasystems.com>
Date:   Tue Apr 24 18:48:25 2018 +0200

    win32: remove FF_PKT->sys_fname attribute and unix_name_to_win32() function

    - sys_fname attribute is only used for win32 and only for debugging
    - f_name can be used instead
    - unix_name_to_win32() is only used for debugging purpose
    - sys_fname & unix_name_to_win32() are not appropriate anymore

Author: Kern Sibbald <kern@sibbald.com>
Date:   Wed Mar 28 13:48:00 2018 +0200

    Add prepare bit to the plugin stream and handle it in the SD

Author: Alain Spineux <alain@baculasystems.com>
Date:   Mon Jan 30 19:00:08 2017 +0100

    restore mtime & atime for symlink

    - use lutimes(), need HAVE_LUTIMES
    - added a #ifdef HAVE_LCHOWN because of "#define lchown chown"