BEE Backport bacula/src/cats/update_postgresql_tables.in
This commit is the result of the squash of the following main commits:

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Wed Apr 29 13:52:04 2020 +0200

    Update SQL scripts for Events table. Catalog format 1022

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Tue Mar 5 11:37:45 2019 +0100

    Modify SQL upgrade scripts for format 1021

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Dec 6 10:19:13 2018 +0100

    Add procedure to upgrade from catalog version 16 to 1020

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Tue Feb 27 16:06:06 2018 +0100

    Allow to copy/migrate jobs with plugins

    Up to now, the unique Job name is used by plugins as a key
    in some cases (for example as a snapshot name).
    The plugin can use this value to compute the backup set.
    For example, snapshot-diff previous current

    When using Copy/Migration, the unique Job name associated with a job
    is updated with a new name, leading to some confusion on the plugin
    side.

    With this patch, we associate the original Job name with the
    Copy/Migration job record in the catalog, and we can send this value
    to the Client. If we copy a job that was migrated, the original job
    is kept from one job record to an other.

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Fri Feb 16 17:47:54 2018 +0100

    Add catalog Job column PriorJob

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Tue Feb 13 14:13:54 2018 +0100

    Add Pool::MaxPoolBytes to the catalog. Catalog version is now 1020

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Mar 23 10:10:58 2017 +0100

    Adapt update_bacula_tables scripts for catalog version 15

Author: Kern Sibbald <kern@sibbald.com>
Date:   Thu Dec 1 10:29:47 2016 +0100

    Fix bug 2275 Postgresql update script failure and add CloudParts in Media table

Author: Kern Sibbald <kern@sibbald.com>
Date:   Tue Oct 11 09:48:34 2016 +0200

    Add new Cloud part info to catalog - update database version to 1019

Author: Kern Sibbald <kern@sibbald.com>
Date:   Mon Aug 1 17:24:28 2016 +0200

    Make update_xxx_tables script explanation clearer

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Tue Apr 5 18:55:10 2016 +0200

    Implement FileMedia feature and FO_OFFSETS for plugin

     - Allow plugins to use the FO_OFFSETS option
     - Add SQL support in cats
     - Add bvfs commands
     - Add FileMedia handling in the Storage Daemon
     - Add use FO_OFFSETS option in test plugin
     - Add new sql scripts to configure.in
     - Update catalog version to 1018

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Jun 11 17:15:34 2015 +0200

    Fix error in update_postgresql_tables.in caused by bad search and replace

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Mon Mar 9 08:23:34 2015 +0100

    Add --stop1016 option to update_postgresql-_tables.in script

      The option is used by the debian upgrade script. Each step is handled
      automatically by the package.

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Tue Feb 24 16:46:46 2015 +0100

    Upgrade catalog version to 1017

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Mon Nov 25 13:53:45 2013 +0100

    Enhance postgresql upgrade script to avoid writing WALs while loading the File table

    Need to use:
    archive_mode=off
    wal_level=minimal

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Sun Nov 3 17:32:19 2013 +0100

    Add missing FileTable column on JobHisto table

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Mon Sep 23 15:56:34 2013 +0200

    Remove the temporary file with the File table export at the end of the update

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Fri Sep 20 16:49:17 2013 +0200

    Add FileTable attribute in Job table

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Sep 19 13:29:23 2013 +0200

    Fix #8269 about VolWrites overflow for PostgreSQL backend

      - Change VolWrites (not really used other than for external statistics) from 32bit to 64bit

        Error: sql_update.c:411 sql_update.c:411 update UPDATE Media SET VolJobs=1,VolFiles=1,VolBlocks=13409927,VolBytes=865101275136,VolMounts=317,VolErrors=0,VolWrites=2160216210,MaxVolBytes=1609538994176,VolStatus='Append',Slot=3,InChanger=1,VolReadTime=3467657,VolWriteTime=681603738721,VolParts=0,LabelType=0,StorageId=3,PoolId=14,VolRetention=86400,VolUseDuration=1,MaxVolJobs=0,MaxVolFiles=0,Enabled=1,LocationId=0,ScratchPoolId=0,RecyclePoolId=0,RecycleCount=314,Recycle=1,ActionOnPurge=0 WHERE VolumeName='005045L5' failed:
    ERROR:  integer out of range

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Wed Sep 18 16:03:16 2013 +0200

    More work on upgrade scripts

     - use work_mem and maintenance_work_mem
     - allow to use pigz or pbzip2 to compress data

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Wed Aug 28 13:49:30 2013 +0200

    More work on migration scripts

     - Fix hardlink-test
     - Ensure that the mysql migration script will stop if having error

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Fri May 3 13:24:07 2013 +0200

    Cleanup update_xxxx_tables.in

    The script is now updating the schema step by step from version 12 to
    version 1015.

Author: Kern Sibbald <kern@sibbald.com>
Date:   Tue Feb 5 12:37:33 2013 +0100

    Add VolABytes to Media record + adapt Bacula code new DB version 1015

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Thu Feb 23 11:39:53 2012 +0100

    Add update procedure from 5.2

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Wed Feb 15 15:27:23 2012 +0100

    Update update_xxx_tables scripts for version 1014

Author: Eric Bollengier <eric@baculasystems.com>
Date:   Mon Jan 30 13:19:07 2012 +0100

    Update update_xxx_tables to convert 12,13 to 14